apiVersion: v1
kind: Namespace
metadata:
  name: nfs-storage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    pod-security.kubernetes.io/enforce: "privileged"
---
apiVersion: v1
kind: Namespace
metadata:
  name: avi-system
  labels:
    pod-security.kubernetes.io/enforce: "privileged"

