apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gatekeeper.yaml
- mutation-psa-policy.yaml

images:
- name: openpolicyagent/gatekeeper
  newName: registry.guzware.net/gatekeeper/gatekeeper
