apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gatekeeper.yaml
- mutation-psa-policy.yaml

images:
- name: openpolicyagent/gatekeeper
  newName: harbor.navneet.pro/proxy-cache/openpolicyagent/gatekeeper
