# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: ako-secret-reader-rolebinding
  namespace: avi-system
subjects:
- kind: ServiceAccount
  name: ako-secret-sa
  namespace: avi-system
roleRef:
  kind: Role
  name: ako-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
