apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- antrea-config-1.yaml
- tkgs-cluster-class-noaz-2.yaml
- argocd-tkc-1-base-app-env-3.yaml
- argocd-tkc-1-base-app-cm-5.yaml
- tkc-cluster-1/applications/foundational/repos/argocd-ako-repo.yaml
- tkc-cluster-1/applications/foundational/repos/argocd-nfs-repo.yaml
- tkc-cluster-1/applications/foundational/ako
  
namespace: ns-1

images:
- name: whoami6443/argocd-hook
  newName: registry.guzware.net/whoami/argocd-hook

