apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-readiness-check
  annotations:
    argocd.argoproj.io/hook: PostSync # This annotation makes it a PreSync hook
    argocd.argoproj.io/hook-delete-policy: HookSucceeded # This tells ArgoCD to delete the hook on success
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    spec:
      containers:
      - name: readiness-check
        image: registry.guzware.net/curl/curl # Using a simple curl image for demonstration
        command: ["sh", "-c"]
        args:
        - >
          until curl -sfk ${CLUSTER_IP}:6443;
          do echo 'Waiting for Kubernetes API...'; sleep 5;
          done;
          echo 'Kubernetes API is up and running!';
      restartPolicy: Never
  backoffLimit: 4

