# role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: ako-secret-reader-role
  namespace: avi-system
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["*"]

